version: '3.9'
services:
  api_server:
    container_name: api_server
    build:
      context: ./api_server
    volumes:
      - ./api_server/app:/app
      - ./api_server/app/wrangler_data:/app/.config/.wrangler
    ports:
      - 8787:8787
    depends_on:
      - db
    tty: true # コンテナの永続化
    environment:
      - TZ=Asia/Tokyo

  db:
    image: mysql:8.0.28
    container_name: db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=hono_openapi_practice
      - TZ=Asia/Tokyo
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql:/var/lib/mysql
